service:
  port: ":9876"
  secretJWT: "yoursecret"

database:
  dataSourceName: "postgres://username:password@host:5432/music_catalog?sslmode=disable"

spotifyConfig:
  clientID: your-spotify-client-id
  clientSecret: your-spotify-client-secret